{
  "uid" : "76cea2acab681fcf",
  "name" : "test_login",
  "fullName" : "tests.test_login#test_login",
  "historyId" : "144503cdd62308bf9f77a1ff306826fa",
  "time" : {
    "start" : 1627408358092,
    "stop" : 1627408358875,
    "duration" : 783
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'login.csv'",
  "statusTrace" : "def test_login():\n    \n        options = Options()\n        options.headless = True\n    \n        driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n        wait = WebDriverWait(driver, 10)\n    \n        try:\n            driver.get('http://localhost:1667/#/login')\n    \n            def find_and_clear(element_xpath):\n                element = driver.find_element_by_xpath(element_xpath)\n                element.clear()\n                return element\n    \n            sign_in_button = driver.find_element_by_xpath('//*[@id=\"app\"]/div/div/div/div/form/button')\n    \n            # data entry:\n>           with open('login.csv', 'r') as login_data:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'login.csv'\n\ntests/test_login.py:32: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'login.csv'",
    "statusTrace" : "def test_login():\n    \n        options = Options()\n        options.headless = True\n    \n        driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n        wait = WebDriverWait(driver, 10)\n    \n        try:\n            driver.get('http://localhost:1667/#/login')\n    \n            def find_and_clear(element_xpath):\n                element = driver.find_element_by_xpath(element_xpath)\n                element.clear()\n                return element\n    \n            sign_in_button = driver.find_element_by_xpath('//*[@id=\"app\"]/div/div/div/div/form/button')\n    \n            # data entry:\n>           with open('login.csv', 'r') as login_data:\nE           FileNotFoundError: [Errno 2] No such file or directory: 'login.csv'\n\ntests/test_login.py:32: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "47028abfe80869bc",
      "name" : "log",
      "source" : "47028abfe80869bc.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "1d316a30d6bf45bd",
      "name" : "stderr",
      "source" : "1d316a30d6bf45bd.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "host",
    "value" : "fv-az83-845"
  }, {
    "name" : "thread",
    "value" : "3933-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "76cea2acab681fcf.json",
  "parameterValues" : [ ]
}